export enum Estado {
    ACTIVO = "ACTIVO",
    INACTIVO = "INACTIVO",
    PENDIENTE = "PENDIENTE",
    RECIBIDO = "RECIBIDO",
    PREPARACION = "EN PREPARACION",
    LISTO = "LISTO",
    RETIRADO = "RETIRADO",
    TERMINADO = "TERMINADO",
    PAGADO = "PAGADO",
    VENCIDO = "VENCIDO",
    CULMINADO = "CULMINADO",
    OCUPADO = "OCUPADO",
    LIBRE = "LIBRE",
    ENTREGADO = "ENTREGADO",
    ALL = "ALL",
    
}
