export enum Estado {
    ACTIVO = "ACTIVO",
    INACTIVO = "INACTIVO",
    PENDIENTE = "PENDIENTE",
    ANULADO = "ANULADO",
    MATRICULADO = "MATRICULADO",
    NO_MATRICULADO = "NO_MATRICULADO",
    RETIRADO = "RETIRADO",
    INSCRIPCION_ABIERTA = "INSCRIPCION_ABIERTA",
    ALL = "ALL",
    TERMINADO = "TERMINADO",
    PAGADO = "PAGADO",
    VENCIDO = "VENCIDO",
    CULMINADO = "CULMINADO"
}
